language: objective-c # lies
osx_image: beta-xcode6.3
before_install: brew unlink xctool && brew install --HEAD xctool
xcode_project: BNRSwiftJSON/BNRSwiftJSON.xcodeproj
matrix:
  include:
    - xcode_sdk: "iphonesimulator"
      xcode_scheme: "BNRSwiftJSON iOS"
    - xcode_sdk: "macosx"
      xcode_scheme: "BNRSwiftJSON Mac"
