language: objective-c # lies
osx_image: xcode7
before_install: brew uninstall xctool && brew install --HEAD xctool
xcode_project: Freddy.xcodeproj
matrix:
  include:
    - xcode_sdk: "macosx"
      xcode_scheme: "Freddy"
    - xcode_sdk: "iphonesimulator"
      xcode_scheme: "MobileFreddy"
