language: objective-c
osx_image: xcode8
install:
  - gem install fastlane --no-rdoc --no-ri --no-document
  - gem install xcpretty --no-rdoc --no-ri --no-document
  - gem install jazzy --no-rdoc --no-ri --no-document
script:
  bundle exec fastlane travis
notifications:
  slack:
    secure: VHcEZcTuVR3gfHIcM9jcxrXgE3tkVIT4gWDLpnK7O4em86dCpaVkLDwr0UcQYxvqGS1J8pQqGZCwyOBsdgaItX52eRDMIez/384B56Vl6eufdLAcwWELIEtHyFkJ6XUjmASICaeeb8SpF/rj89/AXoHU6c8shY13NKtoBBZCGq8=
env:
  global:
    secure: fgx97DOi3+wTHwfyo1LhsXtQolZltBmZFKCfyeq9IWqvJ0wCvFXE3QllD66369LzC5Fz/ipPRwqsd0nH393Nq1xFLAjdZkOhVAc65GjNjKfBQsaKcsIn0/AXd0RIKimzmvBAMHSh0jy3tBKrEQVCJtR6dF6nRoQNC80TxLoDrKg=
