language: objective-c
osx_image: xcode7.2
install:
- gem install xcpretty --no-rdoc --no-ri --no-document
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
script:
- set -o pipefail && xcodebuild -scheme 'Freddy' test | xcpretty -c
- set -o pipefail && xcodebuild -scheme 'MobileFreddy' -sdk iphonesimulator test |
  xcpretty -c
- carthage build --no-skip-current
only:
- master
notifications:
  slack:
    secure: IeneJfJosEW7T8gy6fFrJTWAuxe9IZeID9YCmIFAG8bYs3qeiiyqgbpx/1Z+OFDgtNp4+L+Z6ag+eOVs5I+yvki6fqvz/olEI40gM6toQpN+2epStW3us9hYh0+e0D6zY698tktQNl6XC9P1qepO512H4ZqPrlywBB2Z8bDaAXU=
    on_failure: change
    on_start: never
