language: objective-c # lies
osx_image: beta-xcode6.3
before_install: brew upgrade xctool
xcode_project: BNRSwiftJSON/BNRSwiftJSON.xcodeproj
matrix:
  include:
    - xcode_sdk: "iphonesimulator"
      xcode_scheme: "BNRSwiftJSON iOS"
    - xcode_sdk: "macosx10.10"
      xcode_scheme: "BNRSwiftJSON Mac"
